#!/bin/sh

# source function library
. /etc/init.d/functions

start() {
  
  exec /usr/sbin/lxdm-binary &

}

stop() {
   #  code to stop application
      killproc lxdm
}

case "$1" in 
        start)
           start
           ;;
        stop)
           stop
           ;;
        restart)
           stop
           start
           ;;
        status)
           status lxdm
           ;;
        *)
          echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
        

